### ISSUE TITLE
Static Linking FastRoute

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project-Attic/FastRoute#1]
Hi All,
Thanks for all the work put into the tool with the rest of our flow. I am attempting to test fastRoute now but running into issues with dynamically linked libraries. I am able to build the binary but seeing linker issues when I try to run on a different machine.

Can you please look into statically linking as many libraries? Specifically the following
1. libpng12
2. libz
3. librt
4. libboost_system
5. libboost_filesystem
6. libboost_program_options
7. libQt5PrintSupport
8. libQt5OpenGL
9. libQt5Widgets
10. libQt5Gui
11. libQt5Core

Thanks

cc: @abk-openroad @mgwoo @mik226

**Comment by abk-openroad** [comment]
p.s. Based on Minsoo's go-ahead, I transferred ownership to
The-OpenROAD-Project and made the repository public.

I hope that the last few fixes / improvements are going well.  (Minsoo
mentioned that he was discussing some issues seen in both Nangate45
(overflow) and TSMC65LP (unconnected pins) with Eder et al.)

Let's try to catch up to the complete list of issues (which mostly should
be closed) in tomorrow's 4pm PT call.

BTW, does FastRoute4-lefdef run clean with ASAP7 ?  It seems that this is
one of the standard PDKs used by the RDF flow.

Thanks very much,

-- Andrew
